-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 18:05:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs361_photo_catalog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cs361_photo_catalog` ;

-- -----------------------------------------------------
-- Schema cs361_photo_catalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs361_photo_catalog` DEFAULT CHARACTER SET utf8 ;
USE `cs361_photo_catalog` ;

-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Folders` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Folders` (
  `folderID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parentID` INT NULL,
  PRIMARY KEY (`folderID`),
  UNIQUE INDEX `namel_UNIQUE` (`name` ASC),
  INDEX `parentID_idx` (`parentID` ASC),
  UNIQUE INDEX `folderID_UNIQUE` (`folderID` ASC),
  CONSTRAINT `fk_folders_folders_parentID`
    FOREIGN KEY (`parentID`)
    REFERENCES `cs361_photo_catalog`.`Folders` (`folderID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Albums` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Albums` (
  `albumID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `folderID` INT NULL,
  PRIMARY KEY (`albumID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `folderID_idx` (`folderID` ASC),
  UNIQUE INDEX `albumID_UNIQUE` (`albumID` ASC),
  CONSTRAINT `fk_albums_folders_folderID`
    FOREIGN KEY (`folderID`)
    REFERENCES `cs361_photo_catalog`.`Folders` (`folderID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Photos` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Photos` (
  `photoID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `path` MEDIUMTEXT NOT NULL,
  `albumID` INT NOT NULL,
  PRIMARY KEY (`photoID`),
  INDEX `albumID_idx` (`albumID` ASC),
  UNIQUE INDEX `photoID_UNIQUE` (`photoID` ASC),
  CONSTRAINT `fk_photos_albums_albumID`
    FOREIGN KEY (`albumID`)
    REFERENCES `cs361_photo_catalog`.`Albums` (`albumID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Tags` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Tags` (
  `tagID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tagID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `tagID_UNIQUE` (`tagID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`PhotoTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`PhotoTags` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`PhotoTags` (
  `photoTagID` INT NOT NULL AUTO_INCREMENT,
  `photoID` INT NOT NULL,
  `tagID` INT NOT NULL,
  PRIMARY KEY (`photoTagID`),
  INDEX `photoID_idx` (`photoID` ASC),
  INDEX `tagID_idx` (`tagID` ASC),
  UNIQUE INDEX `photoTagID_UNIQUE` (`photoTagID` ASC),
  UNIQUE INDEX `photoID_tagID_UNIQUE` (`photoID` ASC, `tagID` ASC),
  CONSTRAINT `fk_phototags_photos_photoID`
    FOREIGN KEY (`photoID`)
    REFERENCES `cs361_photo_catalog`.`Photos` (`photoID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phototags_photos_tagID`
    FOREIGN KEY (`tagID`)
    REFERENCES `cs361_photo_catalog`.`Tags` (`tagID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Metadata` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Metadata` (
  `metadataID` INT NOT NULL AUTO_INCREMENT,
  `body` MEDIUMTEXT NOT NULL,
  `photoID` INT NOT NULL,
  PRIMARY KEY (`metadataID`),
  UNIQUE INDEX `metadataID_UNIQUE` (`metadataID` ASC),
  CONSTRAINT `fk_metadata_photos_photoID`
    FOREIGN KEY (`photoID`)
    REFERENCES `cs361_photo_catalog`.`Photos` (`photoID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs361_photo_catalog`.`Thumbnails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`Thumbnails` ;

CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`Thumbnails` (
  `thumbnailID` INT NOT NULL AUTO_INCREMENT,
  `path` MEDIUMTEXT NOT NULL,
  `photoID` INT NOT NULL,
  PRIMARY KEY (`thumbnailID`),
  UNIQUE INDEX `thumbnailID_UNIQUE` (`thumbnailID` ASC),
  CONSTRAINT `fk_thumbnails_photos_photoID`
    FOREIGN KEY (`photoID`)
    REFERENCES `cs361_photo_catalog`.`Photos` (`photoID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `cs361_photo_catalog` ;

-- -----------------------------------------------------
-- Placeholder table for view `cs361_photo_catalog`.`v_all_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs361_photo_catalog`.`v_all_photos` (`Album` INT, `PhotoID` INT, `FileName` INT, `FilePath` INT, `Tags` INT);

-- -----------------------------------------------------
-- procedure sp_create_album
-- -----------------------------------------------------

USE `cs361_photo_catalog`;
DROP procedure IF EXISTS `cs361_photo_catalog`.`sp_create_album`;

DELIMITER $$
USE `cs361_photo_catalog`$$
CREATE PROCEDURE sp_create_album (
	IN p_name varchar(45),
    IN p_folder_id int,
    OUT p_new_album_id int
)
COMMENT 'Add a new album and return album ID'
BEGIN
	IF (p_folder_id IS NULL OR p_folder_id = '') THEN
		INSERT INTO Albums (
			name
		)
		VALUES (
			p_name
		);
    ELSE
		INSERT INTO Albums (
			name,
			folderID
		)
		VALUES (
			p_name,
			p_folder_id
		);
	END IF;

    -- Store the ID of the last inserted row
    SELECT LAST_INSERT_ID() into p_new_album_id;
    -- Display the ID of the last inserted album
    SELECT LAST_INSERT_ID() AS 'new_id';

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_import_photo
-- -----------------------------------------------------

USE `cs361_photo_catalog`;
DROP procedure IF EXISTS `cs361_photo_catalog`.`sp_import_photo`;

DELIMITER $$
USE `cs361_photo_catalog`$$
CREATE PROCEDURE sp_import_photo (
    IN p_name varchar(255),
    IN p_path mediumtext,
    IN p_album_id int,
    OUT p_new_photo_id int
)
COMMENT 'Add a new photo and return photo ID'
BEGIN
    INSERT INTO Photos (
        name,
        path,
        albumID
    )
    VALUES (
        p_name,
        p_path,
        p_album_id
    );

    -- Store the ID of the last inserted row
    SELECT LAST_INSERT_ID() into p_new_photo_id;
    -- Display the ID of the last inserted photo
    SELECT LAST_INSERT_ID() AS 'new_id';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_create_tag
-- -----------------------------------------------------

USE `cs361_photo_catalog`;
DROP procedure IF EXISTS `cs361_photo_catalog`.`sp_create_tag`;

DELIMITER $$
USE `cs361_photo_catalog`$$
CREATE PROCEDURE sp_create_tag (
    IN p_name varchar(45),
    OUT p_new_tag_id int
)
COMMENT 'Create a new tag and return tag ID'
BEGIN
    INSERT INTO Tags (
        name
    )
    VALUES (
        p_name
    );

    -- Store the ID of the last inserted row
    SELECT LAST_INSERT_ID() into p_new_tag_id;
    -- Display the ID of the last inserted photo
    SELECT LAST_INSERT_ID() AS 'new_id';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_add_photo_tag
-- -----------------------------------------------------

USE `cs361_photo_catalog`;
DROP procedure IF EXISTS `cs361_photo_catalog`.`sp_add_photo_tag`;

DELIMITER $$
USE `cs361_photo_catalog`$$
CREATE PROCEDURE sp_add_photo_tag (
    IN p_photo_id int,
    IN p_tag_id int,
    OUT p_new_photo_tag_id int
)
COMMENT 'Add tag to photo and return Photo Tag ID'
BEGIN
    INSERT INTO PhotoTags (
        photoID,
        tagID
    )
    VALUES (
        p_photo_id,
        p_tag_id
    );

    -- Store the ID of the last inserted row
    SELECT LAST_INSERT_ID() into p_new_photo_tag_id;
    -- Display the ID of the last inserted photo tag
    SELECT LAST_INSERT_ID() AS 'new_id';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `cs361_photo_catalog`.`v_all_photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs361_photo_catalog`.`v_all_photos`;
DROP VIEW IF EXISTS `cs361_photo_catalog`.`v_all_photos` ;
USE `cs361_photo_catalog`;
CREATE  OR REPLACE VIEW v_all_photos AS
SELECT
	Albums.name AS Album,
    Photos.photoID AS PhotoID,
    Photos.name AS FileName,
    Photos.path AS FilePath,
    GROUP_CONCAT(IFNULL(Tags.name, '')) AS Tags
FROM
    Albums
    LEFT JOIN Photos ON Albums.albumID = Photos.albumID
    LEFT JOIN PhotoTags ON Photos.photoID = PhotoTags.photoID
    LEFT JOIN Tags ON PhotoTags.tagID = Tags.tagID
GROUP BY Album, PhotoID, FileName, FilePath
ORDER BY Albums.name;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
